cs361fall2018/sprint0

students.txt

Added name, ONID, Github Username (Sachin Sakthivel)

Added name, ONID, Github Username (Sachin Sakthivel)

---

students.txt

Want to add myself to students.txt

added Calvin Gagliano

---

students.txt

Added alexgrejuc at "random" location

Added alexgrejuc

---

students.txt

Added Name

---

students.txt

Edited the students file with my name, ONID id, and user name for github

New commit

---

students.txt

information added to txt file

---

students.txt

There are 2 commits because I had the wrong github account configured for the first commit.

Added name for Kyle Peterson

---

students.txt

Added myself, Isaac Peters, to sprint0 students.txt

Added Isaac Peters

---

students.txt

Pull request to merge changes from zach thompson into master.

Added details to list for zach thompson

---

students.txt

Updated Students

---

students.txt

"added my name, ONID and GitHub username"

---

students.txt

Added my name, ONID, and github username to the student list.

Updated Students List

---

students.txt

Name, onid, and github username were added to the txt file and committed then pushed onto remote repo.

my name, onid, and github username have been added to the txt file

---

students.txt

Put my name/info in students.txt

---

students.txt

Wrote my name, ONID, and github user

Added my info

---

students.txt

added name, onid, github username

---

students.txt

I want to add my information to the list, thank you so much!

sprint0 from Xizhi Yang

---

students.txt

Name, ONID, username

---

students.txt

Added my name, ONID and GitHub username

Pull Request Sprint 0

---

students.txt

Added Self

---

students.txt

I fork the directory to my local system and then add my own information in the sutdent.txt. 
Everything all set!

Haozhe Li info

---

students.txt

I added my name and information to the students.txt file per your request for sprint 0

Added name and info

---

students.txt

	modified:   students.txt

---

students.txt

Added info to random location in students file.
Ethan Mendelson

Added name, onid, and username to students.txt
